version: '3.8'

services:
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
      - "61613:61613"
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
  productor:
    build:
      context: ./productor
    container_name: productor
    ports:
      - "3000:3000"
  consumidor_js:
    build:
      context: ./consumidor/javascript
    container_name: consumidor_js
    ports:
      - "3001:3001"
  consumidor_py:
    build:
      context: ./consumidor/python
    container_name: consumidor_py
    ports:
      - "3002:3002"